### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by zod076** [apalrd/tayga#57]
Hi, just downloaded this but it doesn't compile on FreeBSD 14.2. Will support be added later on ?

**Comment by apalrd** [comment]
There aren't any releases with FreeBSD support, so you would have to compile from Main. I also removed `configure` to simplify the build scripts, so now you just need to run `make` (with gcc + make installed of course). This probably contradicts the readme documentation.

There are also a few FreeBSD-specific nuances (tun adapters must be named tunX, for example, not arbitrary names like on Linux) which probably aren't documented well yet.

What build errors are you getting?

**Comment by apalrd** [comment]
looks like this issue is caused by differences in BSD Make vs GNU Make

To fix your issue, run `make version.h` and then `make`

**Comment by zod076** [comment]
> > looks like this issue is caused by differences in BSD Make vs GNU Make
> > To fix your issue, run `make version.h` and then `make`
> 
> I'll try that and report back shortly thanks.

hm, there's no _version.h_ file.. here are the compile errors:

`root@KUKUBESI:~/staging/apalrd/tayga-0.9.2-10/ > make         
make  all-am
cc -DTAYGA_CONF_PATH=\"/usr/local/etc/tayga.conf\" -I.      -g -Wall -MT nat64.o -MD -MP -MF .deps/nat64.Tpo -c -o nat64.o nat64.c
In file included from nat64.c:18:
./tayga.h:35:10: fatal error: 'linux/if.h' file not found
   35 | #include <linux/if.h>
      |          ^~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make[1]: stopped in /root/staging/apalrd/tayga-0.9.2-10
*** Error code 1

Stop.
make: stopped in /root/staging/apalrd/tayga-0.9.2-10`

I got the source from here: https://github.com/apalrd/tayga/archive/refs/tags/0.9.2-10.tar.gz

**Comment by zod076** [comment]
Ok the setup works on a FreeBSD 14.2 host. Now to see if a vnet jail is able to use this..

From testing, it doesn't seem like it can.. pinging 64:ff9b::1.1.1.1 results in packet lost. I do have a route for 64:ffb::/96 pointing to the jail's vnet interface tho..hm..
